### ISSUE TITLE
Espeak in linux?

### ISSUE THREAD

**Issue by introlinux** [solsticedhiver/mental_calculation#2]
Is the use of Espeak implemented for Linux? I have Espeak installed and appears disabled in the configuration form :-/

**Comment by solsticedhiver** [comment]
Yes. It looks for `/usr/bin/espeak`. If it is installed elsewhere it is not found.

Try to create a symlink from `/usr/bin/espeak` to the actual binary of espeak on command line. For example:

    sudo ln -s /usr/local/bin/espeak /usr/bin/espeak

**Comment by introlinux** [comment]
I have espeak in the correct path then.
~$ which espeak
/usr/bin/espeak

The other thing I thought was about phonon, I have 4.8.0 version in debian, should it work?

**Comment by introlinux** [comment]
More datas, if I force by mentalcalculation.ini the sound to "true", appears checked, but continues disabled and any sound is played.

**Comment by solsticedhiver** [comment]
You need the python module of phonon for pyqt4.

On ubuntu, it is called `python-qt4-phonon`, on other distros I have no idea.

Once I installed that package here, it worked fine.

**Comment by introlinux** [comment]
Perfect!

Thank you.

2015-09-19 21:18 GMT+02:00 solsticedhiver <notifications@github.com>:
