### ISSUE TITLE
Suggestion: pico2wave?

### ISSUE THREAD

**Issue by introlinux** [solsticedhiver/mental_calculation#3]
pico2wave is much more natural and clear than the robotic speaking of espeak.

**Comment by solsticedhiver** [comment]
You can use different voice or even different engine with espeak like mbrola. I don't know much about it but may be you can can dig into this direction ?

Or if you know python, you can hack the script rather easily.

I may look into it...

**Comment by solsticedhiver** [comment]
This is obsolete since the last version use an online TTS engine.
