### ISSUE TITLE
Is this still expected to work?

### ISSUE THREAD

**Issue by lewang** [solsticedhiver/mental_calculation#4]

**Comment by lewang** [comment]
Oops sorry, elaborating.

&nbsp;

I installed dependencies on OSX with homebrew and ran `./mentalcalculation.py` and got 


    Traceback (most recent call last):
      File "./mentalcalculation.py", line 63, in <module>
        from gui import settings, main
    ImportError: cannot import name settings


I also tried from unbunt precise and got the same error.  I don't know enough Python to debug further.

Help?

**Comment by solsticedhiver** [comment]
Yes this is expected to work. Your error is strange and should not happen.

**Comment by TARPTAEYA** [comment]
@lewang you have to install `pyuic5` and execute `pyuic5 settings.ui > settings.py` and `pyuic5 main.ui > main.py`, because `main` and `settings` are present as `.ui` files not as `.py` files so python3 cannot import them directly

**Comment by vck3000** [comment]
> @lewang you have to install `pyuic5` and execute `pyuic5 settings.ui > settings.py` and `pyuic5 main.ui > main.py`, because `main` and `settings` are present as `.ui` files not as `.py` files so python3 cannot import them directly

Could we have this on the README file please? :)
