### ISSUE TITLE
Clicking on Replay crashes the application during Continuous "hands-free" mode

### ISSUE THREAD

**Issue by limsherwin** [solsticedhiver/mental_calculation#7]
Hello,
When Continuous "hands-free" mode is checked and Replay is clicked, the application crash with the following errors:

> Traceback (most recent call last):
>   File "mentalcalculation.py", line 406, in redisplaySequence
>     self.player.stateChanged.disconnect(self.restartPlay)
> TypeError: 'method' object is not connected
> Abort trap: 6

The application also crashes when Start is clicked multiple times after coming out of the Settings dialog.

> Traceback (most recent call last):
>   File "mentalcalculation.py", line 462, in startPlay
>     self.player.stateChanged.disconnect(self.clearLabel)
> TypeError: 'method' object is not connected
> Abort trap: 6

**Comment by solsticedhiver** [comment]
I can't reproduce either of the crashes.

1. The Replay button is supposed to be grayed out when in Continuous "hands-free" mode. So how could you press the button ?

2. What do you mean multiple times ?

Are you on Windows ? or not ?

**Comment by limsherwin** [comment]
I am using MacOS Terminal to run the application.

1. Replay button is un-greyed when the program waits for the answer after each set of problems. The application crashes when I click on it.
2. After clicking Start, I immediately click Start button again before the button has a chance to be labelled as Stop. 

I have created screen recording. It's inside the attached zip file. 

[screenrecord.zip](https://github.com/solsticedhiver/mental_calculation/files/4507209/screenrecord.zip)

**Comment by solsticedhiver** [comment]
I hope I fixed it. But some things needs to be rewritten. It became a mess over time.
